title:  <p align="center"> Shubham Tiwary </p>
logo: /assets/img/Mypicture.jpg
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/shubham-tiwary-6ab8a7163">LinkedIn</a> |
  <a href="https://github.com/tiwari08">GitHub</a>
  <br>   
  A Computer Science student keen to learn and be updated with the latest market trends. I have completed a 6 month
  internship at Earth Lingua PVT LTD from Jan 2020 to June,2020 where I specialized in Python machine learning. 
  During internship, the project assigned was about real time translation application. 
  I created a Virtual voice Assistant named Virtue which is a real time voice translator that can translate over 108 international languages. 
  Virtue has the ability to voice over those languages which is still unavailable via Google API.
  <br>
  </p>
  
  
theme: jekyll-theme-minimal
